version = 1
name    = "Hangar Test Box"
frame   = "local"
margin  = 0.0
action  = "rtl"

[z]
min = 0.0
max = 30.0

[[regions]]
kind   = "include-polygon"
points = [
  [-10.0,   -10.0],
  [100.0, -10.0],
  [100.0, 50.0],
  [-10.0,   50.0]
]