version = 1
name    = "Hangar Test Box"
frame   = "local"
origin  = [45.501500, -73.566500, 30.0]  # lat, lon, alt; or "home"
margin  = 2.0

[z]
min = 0.0
max = 30.0

[[regions]]
kind   = "include-polygon"
points = [
  [-10.0,   -10.0],
  [100.0, -10.0],
  [100.0, 50.0],
  [-10.0,   50.0]
]